/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const IconPhHourglass: (typeof import("~icons/ph/hourglass.jsx"))["default"];
  const IconPhHourglassMedium: (typeof import("~icons/ph/hourglass-medium.jsx"))["default"];
  const IconPhHouse: (typeof import("~icons/ph/house.jsx"))["default"];
}
