const lexicalTheme = {
  ltr: "text-left",
  rtl: "text-right",
  placeholder: "text-muted-foreground opacity-50",
  paragraph: "mb-2 last:mb-0",
  quote: "border-l-4 border-muted pl-4 my-2",
  heading: {
    h1: "text-3xl font-bold mb-4",
    h2: "text-2xl font-semibold mb-3",
    h3: "text-xl font-medium mb-2",
    h4: "text-lg font-medium mb-2",
    h5: "text-base font-medium mb-2",
  },
  list: {
    nested: {
      listitem: "list-none",
    },
    ol: "list-decimal pl-5 mb-2",
    ul: "list-disc pl-5 mb-2",
    listitem: "mb-1",
  },
  image: "max-w-full h-auto",
  link: "text-primary hover:underline",
  text: {
    bold: "font-bold",
    italic: "italic",
    overflowed: "text-ellipsis overflow-hidden",
    hashtag: "text-primary",
    underline: "underline",
    strikethrough: "line-through",
    underlineStrikethrough: "underline line-through",
    code: "bg-muted text-muted-foreground rounded px-1 py-0.5 font-mono text-sm",
  },
  code: "bg-muted text-muted-foreground rounded p-2 font-mono text-sm block whitespace-pre-wrap",
  codeHighlight: {
    atrule: "text-primary",
    attr: "text-primary",
    boolean: "text-accent",
    builtin: "text-accent-foreground",
    cdata: "text-muted-foreground",
    char: "text-accent-foreground",
    class: "text-secondary",
    "class-name": "text-secondary",
    comment: "text-muted-foreground",
    constant: "text-accent",
    deleted: "text-destructive",
    doctype: "text-muted-foreground",
    entity: "text-accent",
    function: "text-secondary",
    important: "text-accent font-bold",
    inserted: "text-success",
    keyword: "text-primary",
    namespace: "text-accent",
    number: "text-accent",
    operator: "text-muted-foreground",
    prolog: "text-muted-foreground",
    property: "text-accent",
    punctuation: "text-muted-foreground",
    regex: "text-accent",
    selector: "text-primary",
    string: "text-success",
    symbol: "text-accent",
    tag: "text-primary",
    url: "text-accent underline",
    variable: "text-destructive",
  },
};

export default lexicalTheme;
